FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY model /app/model

EXPOSE 1234

CMD ["mlflow","models","serve","-m","/app/model","-p","1234","--host","0.0.0.0","--no-conda"]
